version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    ports:
      - "3306:3306"
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
  back_office:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./admin-console/src:/var/www/html
      - bo-storage-volumes:/var/www/html/storage/framework
      - bo-vendor-volumes:/var/www/html/vendor
    depends_on:
      - mysql
  back_office_web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - back_office
    volumes:
      - ./admin-console/src:/var/www/html
      - bo-storage-volumes:/var/www/html/storage/framework
      - bo-vendor-volumes:/var/www/html/vendor
    working_dir: /var/www/html
  public_site:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./public-site/src:/var/www/html
      - po-storage-volumes:/var/www/html/storage/framework
      - po-vendor-volumes:/var/www/html/vendor
    depends_on:
      - mysql
  public_site_web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 7070:7070
    depends_on:
      - public_site
    volumes:
      - ./public-site/src:/var/www/html
      - po-storage-volumes:/var/www/html/storage/framework
      - po-vendor-volumes:/var/www/html/vendor
    working_dir: /var/www/html
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysqldb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "4001:80"
  minio:
    build:
      context: .
      dockerfile: ./infra/minio/Dockerfile
    volumes:
      - "./minio/data:/data:delegated"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root_user
      - MINIO_ROOT_PASSWORD=root_user_password
      - MINIO_SERVER_ADDRESS=http://localhost:9000
      - MINIO_BUCKET_NAME=sample
    command: server /data --console-address :9001
volumes:
  mysql-volume:
  bo-storage-volumes:
  bo-vendor-volumes:
  po-storage-volumes:
  po-vendor-volumes:
